#! /bin/bash
# Dejar al sistema docker que acceda al entorno gráfico
xhost +local:root

# Ejecutar el contenedor comprobando si ha sido creado o no

#variable nombre contenedor
container_name=hgr

#variable nombre imagen
image_name=aosucas499/guadalinex:sigala

#variable carpeta configuración para compartir con el contenedor
STORAGE_FOLDER=/home/$SUDO_USER/HGR
CONFIG_FOLDER=/home/$SUDO_USER/.hgr

#rm -r $STORAGE_FOLDER
#rm -r $CONFIG_FOLDER

#Creamos carpetas para compartir con el container
if [ -d "$STORAGE_FOLDER" ]; then
    echo "Carpeta $STORAGE_FOLDER existe"
    chown -R $SUDO_USER:$SUDO_USER $STORAGE_FOLDER
else
    echo "Creando carpeta $STORAGE_FOLDER"
    mkdir $STORAGE_FOLDER
    chown -R $SUDO_USER:$SUDO_USER $STORAGE_FOLDER
fi

if [ -d "$CONFIG_FOLDER" ]; then
    echo "Carpeta $CONFIG_FOLDER existe"
    chown -R $SUDO_USER:$SUDO_USER $CONFIG_FOLDER
else
    echo "Creando carpeta $CONFIG_FOLDER"
    mkdir $CONFIG_FOLDER
    chown -R $SUDO_USER:$SUDO_USER $CONFIG_FOLDER
fi

docker stop $container_name 
#&& docker rm $container_name

if docker ps -a --format '{{.Names}}' | grep -Eq "^${container_name}\$"; then
   docker start ${container_name}
else

docker run -d --privileged \
--net=host -e DISPLAY="$DISPLAY" \
--volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
--volume="/run/dbus/system_bus_socket:/run/dbus/system_bus_socket" \
-v /dev:/dev \
--ipc=host \
--volume="/etc/group:/etc/group:ro" \
--volume="/etc/passwd:/etc/passwd:ro" --volume="/etc/shadow:/etc/shadow:ro" \
-e USER=$SUDO_USER -e GROUP=$SUDO_USER -e UID=$SUDO_UID -e GID=$SUDO_GID \
-v $CONFIG_FOLDER:/home/$SUDO_USER:rw \
-v $STORAGE_FOLDER:/home/$SUDO_USER/HGR:rw \
--user=$(id -u $SUDO_USER):$(id -g $SUDO_USER) \
--workdir=/home/$SUDO_USER/HGR \
--name ${container_name} ${image_name}

fi

