#!/bin/bash
REPO1=http://centros.edu.guadalinex.org/Edu/catcorner
REPO2=http://centros.edu.guadalinex.org/Edu/catcornerdda
REPO3=http://centros.edu.guadalinex.org/Edu/catcornerdda2
REPO4=http://centros.edu.guadalinex.org/Edu/catcornersc
REPO5=http://centros.edu.guadalinex.org/Edu/precise

sudo apt-get update
sudo echo exit 0 > /usr/sbin/policy-rc.d 
sudo mkdir /usr/share/applications -p 
sudo mkdir /usr/share/desktop-directories -p 
sudo echo "APT { Get { AllowUnauthenticated "1"; }; };" > /etc/apt/apt.conf.d/99allow_unauth 
sudo apt-get install nano screen -y
sudo echo deb $REPO1 guadalinexedu main >> /etc/apt/sources.list.d/guadalinex.list
sudo echo deb $REPO2 guadalinexedu main >> /etc/apt/sources.list.d/guadalinex2.list
sudo echo deb $REPO3 guadalinexedu main >> /etc/apt/sources.list.d/guadalinex3.list
sudo echo deb $REPO4 guadalinexedu main >> /etc/apt/sources.list.d/guadalinex4.list
sudo echo deb $REPO5 precise main >> /etc/apt/sources.list.d/guadalinex5.list


sudo apt-get update
sudo apt-get install cga-hga -y
