#! /bin/bash

clear
# Variables 
#
ROJO="\033[1;31m"
NORMAL="\033[0m"
AZUL="\033[1;34m"
DISTRO=$(lsb_release -cs)
DESKTOP=$XDG_CURRENT_DESKTOP

# Copia el script en el sistema que comprueba que existe la extensión gnome appindicator 
# En caso contrario la descarga y la instala en el usuario local

if [[ $DESKTOP = ubuntu:GNOME || $DESKTOP = ubuntu || $DESKTOP = GNOME || $DESKTOP = UBUNTU || $DESKTOP = gnome ]]
	then
		echo ""
        	echo -e "${ROJO}Escritorio basado en GNOME${NORMAL}"
		echo ""
        	echo -e "${ROJO}Desktop based on GNOME${NORMAL}"
		echo ""
		echo -e "${ROJO}Instalando extensión de GNOME appindicatorsupportrgcjonas${NORMAL}"
		echo ""
        	echo -e "${ROJO}Installing appindicatorsupportrgcjonas GNOME EXTENSION${NORMAL}"
		echo ""
		sleep 3
		sudo cp check-appindicator-gnome-extension /usr/bin
    		sudo chmod +x /usr/bin/check-appindicator-gnome-extension 
		sudo cp check-appindicator-gnome-extension.desktop /etc/xdg/autostart/
    	
    	else
        	echo ""
        	echo -e "${ROJO}Escritorio no basado en GNOME${NORMAL}"
		echo ""
        	echo -e "${ROJO}Desktop not-based on GNOME${NORMAL}"
		echo ""
		echo ""
		echo -e "${AZUL}Desktop environment $XDG_CURRENT_DESKTOP${NORMAL}"
		sleep 4
    	fi

# Establecer la distribución en la que se basa el sistema host.
# 
	if [[ $DISTRO = focal || $DISTRO = ulyana || $DISTRO = ulyssa ]]
	then
        	BASED=focal
    	elif
    	[[ $DISTRO = bionic || $DISTRO = tricia || $DISTRO = tina || $DISTRO = tessa || $DISTRO = tara ]]
    	then
        	BASED=bionic
    	else
        	echo ""
		echo -e "${ROJO}Esta instalación no es compatible con tu sistema${NORMAL}" 
		echo ""
		echo -e "${ROJO}This install process is not compatible with your system${NORMAL}"
		echo ""
		sleep 4
		exit
    	fi

	echo ""
	echo System codename $DISTRO
    	echo ""
	echo System based on Ubuntu $BASED
	echo ""
	sleep 2

# Este script funciona en Ubuntu 18.04, bionic y Ubuntu 20.04, así como las derivadas en linux Mint.
#
	echo ""	
	echo -e "${ROJO}Solicitando contraseña del usuario con derechos de administrador${NORMAL}"
	echo ""
	echo -e "${ROJO}Asking password of the user with administrations rights${NORMAL}"
	echo ""
	sudo echo ""
	
# Borrando antiguos archivos de smartdre o lliurex-smart
#
	echo ""	
	echo -e "${ROJO}Borrando si existen archivos de anteriores instalaciones${NORMAL}"
	echo ""
	echo -e "${ROJO} Deleting if there are files from previous installations${NORMAL}"
	echo ""
	sudo chmod +x uninstall-hgr-dre
	sudo ./uninstall-hgr-dre
  
# Instalar docker
#
	echo ""
	echo -e "${AZUL}Instalando Docker...${NORMAL}"
	echo ""
	echo -e "${AZUL}Instaling Docker...${NORMAL}"
	echo ""
	sudo apt update
	sudo apt install -f
	sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
	sudo apt install -f
	sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
	#sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $DISTRO stable"
	touch docker.list
	echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $BASED stable" > docker.list
	sudo mv docker.list /etc/apt/sources.list.d/docker.list
	sudo apt-key fingerprint 0EBFCD88
	sudo apt update
	sudo apt install docker-ce docker-ce-cli containerd.io -y 
	sudo usermod -aG docker $USER
	sudo rm /etc/apt/sources.list.d/docker.list

# Descarga la imagen docker
#
	echo ""
	echo -e "${AZUL}Descargando la imagen docker, sea paciente...${NORMAL}"
	echo ""
	echo -e "${AZUL}Downloading the docker image, please be patient...${NORMAL}"
	echo ""
  sudo docker pull aosucas499/guadalinex:sigala

# Hacer la aplicación cliente iniciable en cada reinicio y ambas, usables para cualquier usuario sin "sudo"
#
	echo ""
	echo -e "${AZUL}Configurando la app para que arranque en cada inicio de sesión...${NORMAL}"
	echo ""
	echo -e "${AZUL}Settings up the app to boot at init...${NORMAL}"
	echo ""
	sudo cp cga-hgr-server.svg /usr/share/icons/
	# hgr cliente. Se inicia desde el menú educación.
	sudo cp hgr /usr/bin
    	sudo chmod +x /usr/bin/hgr
    	sudo chown root:root zz-hgr
    	sudo chmod 0440 zz-hgr
    	sudo cp zz-hgr /etc/sudoers.d/ 
    	#sudo cp hgr.desktop /etc/xdg/autostart/
    	sudo cp hgr.desktop /usr/share/applications/
	# hgr server. No inicia en cada inicio. Se inicia desde el menú educación.
	sudo cp hgr-server /usr/bin
    	sudo chmod +x /usr/bin/hgr-server
    	sudo chown root:root zz-hgr-server
    	sudo chmod 0440 zz-hgr-server
    	sudo cp zz-hgr-server /etc/sudoers.d/ 
    	sudo cp hgr-server.desktop /usr/share/applications/
	
# Borrar las fuentes después de instalar
	cd ..
	sudo rm -r hgr-dre

echo ""
echo "Reinicie el sistema y la encontrará en el menú Educación"
notify-send "Reinicie el sistema y la encontrará en el menú Educación"
echo ""
