#! /bin/bash

sudo rm -r /home/$USER/HGR

sudo rm -r /home/$USER/HGR-SERVER

sudo rm -r /home/$SUDO_USER/HGR

sudo rm -r /home/$SUDO_USER/HGR-SERVER

sudo rm /etc/xdg/autostart/hgr.desktop

sudo rm  /usr/share/applications/hgr.desktop

sudo rm  /usr/share/applications/hgr-server.desktop

sudo docker stop hgr-server

sudo docker rm hgr-server

sudo docker stop hgr-client

sudo docker rm hgr-client

sudo docker stop hgr

sudo docker rm hgr

sudo docker rmi aosucas499/guadalinex:hgr

sudo docker rmi aosucas499/guadalinex:hga

sudo docker rmi aosucas499/guadalinex:sigala

sudo docker rmi aosucas499/guadalinex:next

sudo docker rmi aosucas499/guadalinex:edu

sudo docker rmi aosucas499/guadalinex

sudo delgroup docker

#sudo apt purge --remove docker-ce docker-ce-cli containerd.io -y
