#! /bin/bash

sudo rm -r /home/$USER/HGR

sudo rm -r /home/$USER/HGR-SERVER

sudo rm -r /home/$USER/.hgr

sudo rm -r /home/$SUDO_USER/HGR

sudo rm -r /home/$SUDO_USER/HGR-SERVER

sudo rm -r /home/$SUDO_USER/.hgr

sudo rm /etc/xdg/autostart/hgr.desktop

sudo rm  /usr/share/applications/hgr.desktop

sudo rm  /usr/share/applications/hgr-server.desktop

sudo docker stop hgr-server hgr-client hgr testing

sudo docker rm hgr-server hgr-client hgr testing

sudo docker rmi aosucas499/guadalinex:hgr

sudo docker rmi aosucas499/guadalinex:hga

sudo docker rmi aosucas499/guadalinex:sigala

sudo docker rmi aosucas499/guadalinex:next

sudo docker rmi aosucas499/guadalinex:edu

sudo docker rmi aosucas499/guadalinex:testing

sudo docker rmi aosucas499/guadalinex

#sudo delgroup docker

#sudo apt purge --remove docker-ce docker-ce-cli containerd.io -y
