#! /bin/bash

	# Instalamos dependencias
	# ---

	sudo apt install -y ssh python-avahi python-qt4 python-qt4-dbus python-netifaces python-sleekxmpp python-webdav x11vnc xtightvncviewer xvnc4viewer vlc libc-ares2 rlwrap avahi-daemon setcd python-dnspython libnss-myhostname

	#Instalamos repositorios debian stretch e instalamos curl
	#

	wget https://raw.githubusercontent.com/aosucas499/sources/main/minino-tde-stretch.list
	sudo mv /etc/apt/sources.list /etc/apt/minino-tde-jessie.list
	sudo mv minino-tde-stretch.list /etc/apt/sources.list
	sudo apt-get update
	sudo apt-get install -y curl

	# Instalamos repositorios guadalinex-next
	#
	
	wget https://raw.githubusercontent.com/aosucas499/sources/main/guadalinex-next.list
	sudo mv guadalinex-next.list /etc/apt/sources.list
	wget http://centros.edu.guadalinex.org/Edu/fenix/pool/main/g/guadalinexedu-keyring/guadalinexedu-keyring_0.2-1_all.deb
	sudo dpkg -i guadalinexedu-keyring_0.2-1_all.deb
	rm guadalinexedu-keyring_0.2-1_all.deb
	sudo apt-get update

	# Instalamos paquetes necesarios sigala desde guadalinex next
	
	sudo apt-get install -y ejabberd 
	sudo apt-get install -y python-sleekxmpp
	sudo apt-get install -y cga-hga

	# Instalamos repositorios debian jessie y dejamos minino en su punto inicial
	#
	
	sudo mv /etc/apt/minino-tde-jessie.list /etc/apt/sources.list
	sudo apt-get update
	
	# Añadimos permisos sudo a la aplicación para que funcione bien con docker y versiones antiguas de guadalinex
	#
	
	sudo sed -i "s/Exec=/Exec=sudo /g" "/usr/share/applications/cga-hgr-client.desktop"
	sudo sed -i "s/Exec=/Exec=sudo /g" "/usr/share/applications/cga-hgr-server.desktop"
	sudo sed -i "s/&&/&& sudo /g" "/etc/xdg/autostart/hgr-autostart.desktop"

	
	# Añadimos permisos sudo a cualquier usuario del sistema, aunque no tenga derechos de administrador
	#
	
	cd /home/$USER
	sudo cp /etc/sudoers.d/ejabberd-cgaconfig .
	sudo rm /etc/sudoers.d/ejabberd-cgaconfig
	sudo chown $USER:$USER ejabberd-cgaconfig 
	sudo chmod 765 ejabberd-cgaconfig
	sudo echo "ALL     ALL=NOPASSWD:/usr/bin/cga-hgr-client" >> ejabberd-cgaconfig
	sudo echo "ALL     ALL=NOPASSWD:/usr/bin/cga-hgr-server" >> ejabberd-cgaconfig
	sudo chown root:root ejabberd-cgaconfig
	sudo chmod 0440 ejabberd-cgaconfig
	sudo mv ejabberd-cgaconfig /etc/sudoers.d/

# Creamos parche a aplicar
    # ---

    # Nos aseguramos que no exista el fichero (en caso contrario añadiría 
    # contenido y daría error al no ser un parche válido)

    rm -f /tmp/sigala-install.patch
    
    # Creamos el parche aquí para evitar el fichero tools/sigala-install.patch 
    # para que funcionen las actualizaciones automáticas de customize-minino 
    # (hasta que no hagamos un "git pull" no podemos depender de ficheros adicionales)

    cat << EOF >> /tmp/sigala-install.patch
--- /tmp/davclient.py	2021-02-19 19:46:49.711549295 +0100
+++ /tmp/davclient-new.py	2021-02-19 19:49:41.812319843 +0100
@@ -81,6 +81,9 @@
         else:
             raise Exception, 'Unsupported scheme'
         
+        if '\r' in path:
+            path=path.replace('\r','')
+            
         self._connection.request(method, path, body, headers)
             
         self.response = self._connection.getresponse()
EOF

	# Aplicamos parche que corrige el encoding al compartir ficheros
	# ---

	sudo patch /usr/lib/python2.7/dist-packages/hga/controlcompartir/cliente/davclient.py /tmp/sigala-install.patch


