#!/bin/bash
REPO1=http://centros.edu.guadalinex.org/Edu/fenix
REPO2=http://centros.edu.guadalinex.org/Edu/fenixsc
REPO3=http://centros.edu.guadalinex.org/Edu/fenixscmd/
REPO4=http://centros.edu.guadalinex.org/Edu/fenixscpdi/
#REPO5=http://centros.edu.guadalinex.org/Edu/precise

sudo apt-get update
sudo echo exit 0 > /usr/sbin/policy-rc.d 
sudo mkdir /usr/share/applications -p 
sudo mkdir /usr/share/desktop-directories -p 
#sudo echo "APT { Get { AllowUnauthenticated "1"; }; };" > /etc/apt/apt.conf.d/99allow_unauth 
sudo apt-get install nano screen -y
sudo echo deb $REPO1 guadalinexedu main >> /etc/apt/sources.list.d/guadalinex.list
sudo echo deb $REPO2 guadalinexedu main >> /etc/apt/sources.list.d/guadalinex2.list
sudo echo deb $REPO3 guadalinexedu main >> /etc/apt/sources.list.d/guadalinex3.list
sudo echo deb $REPO4 guadalinexedu main >> /etc/apt/sources.list.d/guadalinex4.list
#sudo echo deb $REPO5 precise main >> /etc/apt/sources.list.d/guadalinex5.list

sudo apt-get update

wget http://centros.edu.guadalinex.org/Edu/fenix/pool/main/g/guadalinexedu-keyring/guadalinexedu-keyring_0.2-1_all.deb
sudo dpkg -i guadalinexedu-keyring_0.2-1_all.deb

wget http://centros.edu.guadalinex.org/Edu/precise/pool/main/r/rlwrap/rlwrap_0.37-2_i386.deb && sudo dpkg -i rlwrap_0.37-2_i386.deb

wget http://centros.edu.guadalinex.org/Edu/precise/pool/main/n/nodejs/nodejs_0.10.37-1_i386.deb && sudo dpkg -i nodejs_0.10.37-1_i386.de

sudo apt-get install curl -y 

wget http://centros.edu.guadalinex.org/Edu/precise/pool/main/e/etherpad-lite/etherpad-lite_1.5.7-3_all.deb && sudo dpkg -i etherpad-lite_1.5.7-3_all.deb

sudo apt-get install libgdbm3 -y

wget http://security.ubuntu.com/ubuntu/pool/main/p/perl/perl-modules-5.22_5.22.1-9ubuntu0.9_all.deb && wget http://security.ubuntu.com/ubuntu/pool/main/p/perl/libperl5.22_5.22.1-9ubuntu0.9_i386.deb && wget http://security.ubuntu.com/ubuntu/pool/main/p/perl/perl_5.22.1-9ubuntu0.9_i386.deb && wget http://security.ubuntu.com/ubuntu/pool/main/p/perl/perl-base_5.22.1-9ubuntu0.9_i386.deb && wget http://security.ubuntu.com/ubuntu/pool/main/t/tzdata/tzdata_2020a-0ubuntu0.19.10_all.deb && wget http://security.ubuntu.com/ubuntu/pool/main/m/mysql-5.7/mysql-common_5.7.32-0ubuntu0.16.04.1_all.deb && wget http://security.ubuntu.com/ubuntu/pool/main/m/mysql-5.7/libmysqlclient20_5.7.32-0ubuntu0.16.04.1_i386.deb

sudo dpkg -i *.deb

sudo apt-get install cga-hga -y
