#!/bin/bash
REPO1=http://centros.edu.guadalinex.org/Edu/catcorner
REPO2=http://centros.edu.guadalinex.org/Edu/catcornerdda
REPO3=http://centros.edu.guadalinex.org/Edu/catcornerdda2
REPO4=http://centros.edu.guadalinex.org/Edu/catcornersc
REPO5=http://centros.edu.guadalinex.org/Edu/precise
REPO6=http://centros.edu.guadalinex.org/Edu/precisedda
REPO7=http://centros.edu.guadalinex.org/Edu/precisedda2

sudo apt-get update
#sudo echo exit 0 > /usr/sbin/policy-rc.d 
sudo mkdir /usr/share/applications -p 
sudo mkdir /usr/share/desktop-directories -p 
#sudo echo "APT { Get { AllowUnauthenticated "1"; }; };" > /etc/apt/apt.conf.d/99allow_unauth 

# crear repos guadalinex
sudo mv /etc/apt/sources.list /etc/apt/sources.list.save 
touch guadalinex.list
touch guadalinex2.list
touch guadalinex3.list
touch guadalinex4.list
touch guadalinex5.list
touch guadalinex6.list
touch guadalinex7.list

# Para Guadalinex edu activamos repos 1 y 5.
#echo deb $REPO1 guadalinexedu main > guadalinex.list
echo deb $REPO5 precise main > guadalinex5.list

# Para la versión de la tablet de 9v cargador negro, los repos 2 y 6
echo deb $REPO2 guadalinexedu main > guadalinex2.list
echo deb $REPO6 precise main > guadalinex6.list

# Para la versión de la tablet de 5v cargador blanco, los repos 3 y 7
#echo deb $REPO3 guadalinexedu main > guadalinex3.list
#echo deb $REPO7 precise main > guadalinex7.list

#repo común 
echo deb $REPO4 guadalinexedu main > guadalinex4.list

#mover repos guadalinex
sudo mv *.list /etc/apt/sources.list.d/

#firma para instalar paquetes Guadalinex
wget http://guadalinex-edu.cica.es/Edu/catcornerdda/pool/main/g/guadalinexedu-keyring/guadalinexedu-keyring_0.1-10_all.deb
sudo dpkg -i guadalinexedu-keyring_0.1-10_all.deb

sudo rm *.deb
sudo apt-get update
sudo apt-get install cga-hga -y
